language: perl
sudo: false

install:
  - perlbrew list
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - dzil test -v

env:
  global:
    - ALIEN_BASE_NO_ABMB=1
  matrix:
    - ALIEN_INSTALL_TYPE=system
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_CMAKE_FROM_SOURCE=1
